image: docker:latest
services:
  - docker:dind
stages:
  - build
  - deploy
build-master:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
build-normal:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:1.0.$CI_PIPELINE_IID-$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:1.0.$CI_PIPELINE_IID-$CI_COMMIT_REF_SLUG"
  only:
    - develop
deploy:
  image: alpine:latest
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER_1@$SERVER_IP_1 "/usr/bin/zsh run-${CI_PROJECT_NAME}.sh 1.0.$CI_PIPELINE_IID-$CI_COMMIT_REF_SLUG"
  only:
    - develop
