export const Routes = {
  SIGN_IN: '/sign-in',
  FORGOT_PASSWORD: '/forgot-password',
  HOME: '/',
  ORDER_LIST: '/orders',
  ADD_DATA: '/add-data/{packageId}/{simId}',
  PROFILE: '/profile',
  LIST_AGENCY: '/agencys',
  RECHARGE: '/recharges',
  ORDER: '/orders',
  ORDER_ERROR: '/orders-error',
  RECHARGE_PACKAGE: '/recharge/package',
  AGENCY_DETAIL: '/agencys/{id}',
  SUPPORT: '/support',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/{id}',
  CARTS: '/carts',
  CREATE_SUB_AGENCY: '/agencys/create-agency',
  ORDER_DETAIL: '/orders/{id}',
  SELECTE_PACKAGE: '/products/select-package',
  LOG: '/logs',
  DEBT_LIMIT: '/settings/debt-limit',
  SETTINGS: '/settings',
  SETTING_COMMISSION: '/settings/commissions',
};
