export type ProductCardType = {
  code: string;
  country: string;
  data: string;
  dataVal: number;
  description: string;
  flag: string;
  for_type: string;
  group: null;
  popular: null;
  price_to_app: number;
  price_to_ctv: null;
  price_to_forfun: null;
  price_to_partner: null;
  productid: string;
  provider: string;
  sku: string;
  validity: string;
  vi_description: null;
  vsku: string;
  xplori_productid: number;
};
